//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JazzMusicians.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Musician
    {
        public int Id { get; set; }
        public string Thumbnail { get; set; }

        [Required(ErrorMessage = "Name Required!")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Instrument(s) Required!")]
        public string Instruments { get; set; }
        public string Years { get; set; }
        public string Description { get; set; }
    }
}
